version: '3.9'

services:
  # PHP Service
  php:
    build: .
    container_name: laravel-php
    volumes:
      - ./:/var/www/html # Mount the current directory into the container
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini # Optional: Custom PHP config
    depends_on:
      - mariadb
    working_dir: /var/www/html

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./:/var/www/html # Mount the Laravel project
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Custom Nginx config
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: laravel-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Gw3nd0l1jn # Root password for MariaDB
      MYSQL_DATABASE: aquiltingsecret        # Default database
      MYSQL_USER: Gwendolijn          # Non-root user
      MYSQL_PASSWORD: T@@m5  # Password for non-root user
    ports:
      - "3306:3306" # Expose MariaDB on port 3306

  # Optional: phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: mariadb # Service name of the MariaDB container
      MYSQL_ROOT_PASSWORD: Gw3nd0l1jn
    ports:
      - "8081:80" # Access phpMyAdmin via localhost:8081
    depends_on:
      - mariadb

# Networks
networks:
  default:
    driver: bridge
